/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "myovxeobnhwkjuybdvwg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15b3Z4ZW9ibmh3a2p1eWJkdndnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNDQyOTEsImV4cCI6MjA3NjkyMDI5MX0.klTffIWBW9T-pTYNYiyGFVwyN_-uIVV0M-P4omTtVyE";